name: Publish to NuGet (.org)

on:
  push:
    tags:                          # Pattern matched against refs/tags
      - 'v[0-9]+.[0-9]+.[0-9]+'    # Push events to every tag matching e.g. v0.0.1

jobs:
  pack-and-publish:
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 10.0.x

      - name: dotnet pack
        run: dotnet cake.cs --target=pack --configuration=Release

      - name: NuGet login (OIDC â†’ temp API key) # Get a short-lived NuGet API key
        uses: NuGet/login@v1
        id: login
        with:
          user: dominiksta
    
      - name: NuGet push
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json